server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dudebase
        username: root
        password: ''
    flyway:
        schemas: dudebase
        url: jdbc:mysql://localhost:3306
        locations: classpath:/flyway
        check-location: true
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                type: trace
                use_sql_comments: true
